tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "autoconf"
brew "automake"
brew "openssl@1.1"
brew "brew-cask-completion"
brew "brew-gem"
brew "brew-pip"
brew "bsdmake"
brew "freetype"
brew "fontconfig"
brew "xz"
brew "python@3.9"
brew "pkg-config"
brew "cmake"
brew "cmatrix"
brew "cocoapods"
brew "coreutils"
brew "gnu-tar"
brew "dpkg"
brew "elinks"
brew "exiftool"
brew "sdl2"
brew "ffmpeg"
brew "figlet"
brew "fortune"
brew "gcc"
brew "gdb"
brew "git"
brew "gnu-sed"
brew "go"
brew "hashcat"
brew "htop"
brew "imagemagick"
brew "jq"
brew "ldid"
brew "libusbmuxd"
brew "lolcat"
brew "ruby"
brew "macvim"
brew "mas"
brew "nasm"
brew "node"
brew "nativefier"
brew "neofetch"
brew "nmap"
brew "openjdk"
brew "p7zip"
brew "pngcheck"
brew "rsync"
brew "sl"
brew "speedtest-cli"
brew "telnet"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "whois"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "zzz"
cask "adoptopenjdk"
cask "android-platform-tools"
cask "appcleaner"
cask "daisydisk"
cask "discord"
cask "firefox"
cask "font-fira-code"
cask "hex-fiend"
cask "iina"
cask "melonds"
cask "mpv"
cask "plex"
cask "slack"
cask "steam"
cask "visual-studio-code"
cask "wireshark"
cask "xquartz"
mas "1Password 7", id: 1333542190
mas "Dark Reader for Safari", id: 1438243180
mas "Deliveries", id: 924726344
mas "Jump Desktop", id: 524141863
mas "Keynote", id: 409183694
mas "Notability", id: 360593530
mas "Pages", id: 409201541
mas "Paste", id: 967805235
mas "Speedtest", id: 1153157709
mas "Tampermonkey", id: 1482490089
mas "The Unarchiver", id: 425424353
mas "Wipr", id: 1320666476
mas "Yoink", id: 457622435
